import "leaflet/dist/leaflet.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/NavBar";
import Footer from "@/components/Shared/Footer";
import { SessionProvider } from "next-auth/react";
import Providers from "./Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Advisory Evaluator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
        <Providers>
           <Navbar />
          
          {children}
          
 
          </Providers>

       
      </body>
    </html>
  );
}
